### PR TITLE
SBT plugin basis

### LINKED ISSUE #70: Write an SBT plugin

### PR DESCRIPTION
**Pull request by abgruszecki**
This PR adds a sub-project with SBT configuration that makes `sbt doc` use Scala3doc instead of Dottydoc.

The idea is to later on add this SBT configuration to dotty-sbt-plugin.

Closes #70.

### CODE REVIEW

**Comment by abgruszecki** [comment]
@pikinier20 @romanowski can I get the review on this?

The PR adds SBT integration and the `example-project` subproject, which can be document using the integration. To document it, one needs to run `cd dokkaJavaApi && ./gradlew publishToMavenLocal ; sbt publishLocal ; sbt example-project/doc`. The result is in `output/example-project`.

The key idea with SBT integration is that internal SBT code wants to call the `dotty.tools.dottydoc.Main#process` method (see source), and it's just much easier to implement it rather than to modify SBT source. That method is passed Dotty arguments and the root compiler context, so we need to "thread" them into our internals. To do that, `DocConfiguration` is now an enum with two variants, and our Dokka plugin uses that enum to distinguish between where it was called from (CLI or SBT) and proceeds accordingly.

**Comment by abgruszecki** [comment]
Rebase on master, some changes needed to be made since newer version of SBT changes how `scalacOptions` are passed to us in the `doc` task.

**Comment by abgruszecki** [comment]
@pikinier20 @romanowski can I get a review on this? The most important thing to check is whether the way I hooked into Dokka plugin architecture makes sense. See above for longer explanation https://github.com/lampepfl/scala3doc/pull/162#issuecomment-686560169.

**Comment by abgruszecki** [comment]
Result of rendering the example project through the SBT plugin can be found here: https://scala3doc.s3.eu-central-1.amazonaws.com/pr-162/example-project/example-project/index.html.

**Review by romanowski — APPROVED** [review]

**Pull request merged**
