### PR TITLE
Some frontend improvements

### PR DESCRIPTION
**Pull request by TheElectronWill**
- Fixes items 1 and 5 of #227 (search button, search window)
- Improves the first 3 points raised in #200 (sidebar arrows, only one search, logo links to root)

I've tried something to make the search button more visible (namely, make it red). It's just a test for now, what do you think?

### CODE REVIEW

**Comment by romanowski** [comment]
> I've tried something to make the search button more visible (namely, make it red). It's just a test for now, what do you think?

I like it. 

> only one search

I am not sure about this. We've got 2 different searches, one (removed in this PR) is for pages (this including documentation) and one is for signatures. I think we can have both especially if we make clear in our UI design that one for pages is filtering the list of left and one on right do full-depth search.

Another option would be to split results into 2 categories (pages and entries) somewhat similar what scaladosc does. 

@pikinier20 @abgruszecki what do you think?

**Comment by pikinier20** [comment]
I think we can add pages (these that are not currently navigable with main searchbar, like documentation pages) to the main searchbar, and drop this one on LHS. Then we can split results in 2 categories or just name them: `Page $name` and show them with other results.

**Comment by pikinier20** [comment]
According to #200 , there's also a problem with clicking menu arrows. You made them bigger, but I've discovered that there's also a problem with size of "clickable" field. It has only `padding-right` property which makes it feel displaced to the right, height of this field is also not so big which results in feeling that you need to point straight in the middle of arrow. I've repaired it once by setting: 
```CSS
.sideMenuPart .navButton {
//...
padding-right: 14px;
padding: 10px;
}
```
and remove padding attribute from `.sideMenuPart > .overview`

**Comment by TheElectronWill** [comment]
> height of this field is also not so big which results in feeling that you need to point straight in the middle of arrow. I've repaired it once by setting: [...] 
> and remove padding attribute from `.sideMenuPart > .overview`

It works when there is an arrow, but single entries would have no padding, isn't it?
image

EDIT: with some padding on `.sideMenuPart a` it's ok :)

**Comment by abgruszecki** [comment]
I also think that we should integrate page search into the "main" search. Right now we have three search fields and it's just very confusing as to which one should be used. I like @pikinier20's suggestion that in the main search, pages should simply be prefixed with "page". It'd also be good if the "main" search detected if the input began with a "special" keyword (such as "page", "class") and understood that this meant that only that specific category should be searched.

Reg. the PR in general: LGTM!

**Comment by romanowski** [comment]
Ok, I am merging the PR then :)

**Pull request merged**
